
import React, { createContext, useState, useEffect, ReactNode, useCallback } from 'react';
import { TranslationKey } from '../types';

// --- TRANSLATIONS ---
const translations = {
  en: {
    'sidebar.viewAs': 'View as',
    'sidebar.dashboard': 'Dashboard',
    'sidebar.calendar': 'Calendar',
    'sidebar.chat': 'Chat & Messaging',
    'sidebar.menu': 'Menu',
    'sidebar.slider': 'Sliders',
    'sidebar.books': 'Books',
    'sidebar.news': 'News',
    'sidebar.activities': 'Activities',
    'sidebar.magazine': 'Magazine',
    'sidebar.articles': 'Articles',
    'sidebar.courses': 'Courses',
    'sidebar.publications': 'Institutional Publications',
    'sidebar.infographics': 'Infographics',
    'sidebar.videos': 'Videos',
    'sidebar.testimonials': 'Testimonials',
    'sidebar.partners': 'Partners',
    'sidebar.footer': 'Footer',
    'sidebar.about': 'About',
    'sidebar.users': 'Users',
    'sidebar.logs': 'Activity Logs',
    'sidebar.light': 'Light',
    'sidebar.dark': 'Dark',
    'header.searchPlaceholder': 'Search content, articles, pages...',
    'Main': 'Main',
    'Content': 'Content',
    'Media': 'Media',
    'Site': 'Site',
    'Admin': 'Administration',
    'dashboard.greeting': 'Good morning, James',
    'dashboard.subGreeting': "Here's a quick overview of your day",
    'card.title.thingsToDo': 'Things to look into',
    'card.title.payroll': 'Payroll',
    'card.title.directReports': 'Your Direct Reports',
    'card.title.timeOffRequests': 'Time off Requests',
    'card.title.shortcuts': 'My Shortcuts',
    'card.title.upcomingHolidays': 'Upcoming Holidays',
    'card.title.upcomingBirthdays': 'Upcoming Birthday',
    'action.completeAccountSetup': 'Complete Account Setup',
    'action.addMissingDetails': 'Add some missing details to hiring services.',
    'action.finishSetup': 'Finish Setup',
    'action.submitDocs': 'Submit Required Onboarding Documents',
    'action.ensureOnboarding': 'We need to few more details for make sure onboarding goes smoothly.',
    'action.uploadDocs': 'Upload Documents',
    'action.setupDirectDeposit': 'Set Up Direct Deposit for Payroll',
    'action.enterPaymentDetails': 'Enter payment details for accurate payroll processing.',
    'action.setPaymentMethod': 'Set Payment Method',
    'action.reviewTimeOff': 'Review Pending Time-Off Requests',
    'action.requestsNeedAttention': '1 request to needs your attention',
    'action.reviewRequests': 'Review Requests',
    'payroll.submissionToday': 'Payroll submission in today',
    'payroll.grossPay': 'Gross Pay',
    'payroll.deductions': 'Deductions',
    'payroll.taxes': 'Taxes',
    'payroll.benefits': 'Benefits',
    'payroll.others': 'Others',
    'payroll.viewAll': 'View all payroll',
    'reports.viewAll': 'View all',
    'timeOff.next30Days': 'Next 30 days',
    'timeOff.reject': 'Reject',
    'timeOff.approve': 'Approve',
    'shortcuts.timeTracking': 'Time Tracking',
    'shortcuts.contacts': 'Contacts',
    'shortcuts.incomeTax': 'Income Tax',
    'shortcuts.addInfo': 'Add Information',
  },
  ar: {
    'sidebar.viewAs': 'عرض كـ',
    'sidebar.dashboard': 'لوحة التحكم',
    'sidebar.calendar': 'التقويم',
    'sidebar.chat': 'الدردشة والرسائل',
    'sidebar.menu': 'القائمة',
    'sidebar.slider': 'السلايدر',
    'sidebar.books': 'الكتب',
    'sidebar.news': 'الأخبار',
    'sidebar.activities': 'الأنشطة',
    'sidebar.magazine': 'المجلة',
    'sidebar.articles': 'المقالات',
    'sidebar.courses': 'الدورات',
    'sidebar.publications': 'المنشورات المؤسسية',
    'sidebar.infographics': 'الإنفوجرافيك',
    'sidebar.videos': 'الفيديوهات',
    'sidebar.testimonials': 'الشهادات',
    'sidebar.partners': 'الشركاء',
    'sidebar.footer': 'التذييل',
    'sidebar.about': 'حول',
    'sidebar.users': 'المستخدمون',
    'sidebar.logs': 'سجل النشاطات',
    'sidebar.light': 'فاتح',
    'sidebar.dark': 'داكن',
    'header.searchPlaceholder': 'البحث عن المحتوى والمقالات...',
    'Main': 'الرئيسية',
    'Content': 'المحتوى',
    'Media': 'الوسائط',
    'Site': 'الموقع',
    'Admin': 'الإدارة',
    'dashboard.greeting': 'صباح الخير، جيمس',
    'dashboard.subGreeting': 'إليك نظرة سريعة على يومك',
    'card.title.thingsToDo': 'أشياء للنظر فيها',
    'card.title.payroll': 'كشف الرواتب',
    'card.title.directReports': 'تقاريرك المباشرة',
    'card.title.timeOffRequests': 'طلبات الإجازة',
    'card.title.shortcuts': 'اختصاراتي',
    'card.title.upcomingHolidays': 'العطلات القادمة',
    'card.title.upcomingBirthdays': 'أعياد الميلاد القادمة',
    'action.completeAccountSetup': 'إكمال إعداد الحساب',
    'action.addMissingDetails': 'أضف بعض التفاصيل المفقودة لخدمات التوظيف.',
    'action.finishSetup': 'إنهاء الإعداد',
    'action.submitDocs': 'إرسال مستندات الانضمام المطلوبة',
    'action.ensureOnboarding': 'نحتاج إلى بعض التفاصيل الإضافية لضمان سير عملية الانضمام بسلاسة.',
    'action.uploadDocs': 'تحميل المستندات',
    'action.setupDirectDeposit': 'إعداد الإيداع المباشر للرواتب',
    'action.enterPaymentDetails': 'أدخل تفاصيل الدفع لمعالجة دقيقة للرواتب.',
    'action.setPaymentMethod': 'تعيين طريقة الدفع',
    'action.reviewTimeOff': 'مراجعة طلبات الإجازة المعلقة',
    'action.requestsNeedAttention': 'طلب واحد يحتاج إلى انتباهك',
    'action.reviewRequests': 'مراجعة الطلبات',
    'payroll.submissionToday': 'تقديم كشف الرواتب اليوم',
    'payroll.grossPay': 'الراتب الإجمالي',
    'payroll.deductions': 'الخصومات',
    'payroll.taxes': 'الضرائب',
    'payroll.benefits': 'المنافع',
    'payroll.others': 'أخرى',
    'payroll.viewAll': 'عرض كل الرواتب',
    'reports.viewAll': 'عرض الكل',
    'timeOff.next30Days': 'الـ 30 يومًا القادمة',
    'timeOff.reject': 'رفض',
    'timeOff.approve': 'موافقة',
    'shortcuts.timeTracking': 'تتبع الوقت',
    'shortcuts.contacts': 'جهات الاتصال',
    'shortcuts.incomeTax': 'ضريبة الدخل',
    'shortcuts.addInfo': 'إضافة معلومات',
  },
  fa: {
    'sidebar.viewAs': 'مشاهده به عنوان',
    'sidebar.dashboard': 'داشبورد',
    'sidebar.calendar': 'تقویم',
    'sidebar.chat': 'چت و پیام‌رسانی',
    'sidebar.menu': 'منو',
    'sidebar.slider': 'اسلایدر',
    'sidebar.books': 'کتاب‌ها',
    'sidebar.news': 'اخبار',
    'sidebar.activities': 'فعالیت‌ها',
    'sidebar.magazine': 'مجله',
    'sidebar.articles': 'مقالات',
    'sidebar.courses': 'دوره‌ها',
    'sidebar.publications': 'انتشارات سازمانی',
    'sidebar.infographics': 'اینفوگرافیک',
    'sidebar.videos': 'ویدیوها',
    'sidebar.testimonials': 'نظرات',
    'sidebar.partners': 'شرکا',
    'sidebar.footer': 'فوتر',
    'sidebar.about': 'درباره',
    'sidebar.users': 'کاربران',
    'sidebar.logs': 'گزارش فعالیت‌ها',
    'sidebar.light': 'روشن',
    'sidebar.dark': 'تاریک',
    'header.searchPlaceholder': 'جستجوی محتوا و مقالات...',
    'Main': 'اصلی',
    'Content': 'محتوا',
    'Media': 'رسانه',
    'Site': 'سایت',
    'Admin': 'مدیریت',
    'dashboard.greeting': 'صبح بخیر، جیمز',
    'dashboard.subGreeting': 'در اینجا یک نمای کلی از روز شما وجود دارد',
    'card.title.thingsToDo': 'چیزهایی برای بررسی',
    'card.title.payroll': 'حقوق و دستمزد',
    'card.title.directReports': 'گزارش های مستقیم شما',
    'card.title.timeOffRequests': 'درخواست های مرخصی',
    'card.title.shortcuts': 'میانبرهای من',
    'card.title.upcomingHolidays': 'تعطیلات آینده',
    'card.title.upcomingBirthdays': 'تولدهای آینده',
    'action.completeAccountSetup': 'تکمیل راه اندازی حساب',
    'action.addMissingDetails': 'جزئیات ناقص را برای خدمات استخدامی اضافه کنید.',
    'action.finishSetup': 'پایان راه اندازی',
    'action.submitDocs': 'ارسال مدارک مورد نیاز برای ورود',
    'action.ensureOnboarding': 'ما به چند جزئیات دیگر نیاز داریم تا مطمئن شویم ورود به سیستم به آرامی انجام می شود.',
    'action.uploadDocs': 'بارگذاری اسناد',
    'action.setupDirectDeposit': 'راه اندازی واریز مستقیم برای حقوق و دستمزد',
    'action.enterPaymentDetails': 'جزئیات پرداخت را برای پردازش دقیق حقوق و دستمزد وارد کنید.',
    'action.setPaymentMethod': 'تنظیم روش پرداخت',
    'action.reviewTimeOff': 'بررسی درخواست های مرخصی در حال انتظار',
    'action.requestsNeedAttention': '۱ درخواست به توجه شما نیاز دارد',
    'action.reviewRequests': 'بررسی درخواست ها',
    'payroll.submissionToday': 'ارسال حقوق و دستمزد امروز',
    'payroll.grossPay': 'حقوق ناخالص',
    'payroll.deductions': 'کسورات',
    'payroll.taxes': 'مالیات',
    'payroll.benefits': 'مزایا',
    'payroll.others': 'دیگران',
    'payroll.viewAll': 'مشاهده تمام حقوق ها',
    'reports.viewAll': 'مشاهده همه',
    'timeOff.next30Days': '۳۰ روز آینده',
    'timeOff.reject': 'رد کردن',
    'timeOff.approve': 'تایید',
    'shortcuts.timeTracking': 'ردیابی زمان',
    'shortcuts.contacts': 'مخاطبین',
    'shortcuts.incomeTax': 'مالیات بر درآمد',
    'shortcuts.addInfo': 'افزودن اطلاعات',
  },
};

type Language = 'en' | 'ar' | 'fa';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: TranslationKey) => string;
  dir: 'ltr' | 'rtl';
}

export const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');
  const [dir, setDir] = useState<'ltr' | 'rtl'>('ltr');

  useEffect(() => {
    const newDir = ['ar', 'fa'].includes(language) ? 'rtl' : 'ltr';
    setDir(newDir);
    document.documentElement.lang = language;
    document.documentElement.dir = newDir;
  }, [language]);

  const t = useCallback((key: TranslationKey): string => {
    return translations[language][key] || translations.en[key];
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
};
